site_name: vSuite Documentation
site_description: Documentation for the vSuite Package
site_author: vSuite Development & Triage Team
site_url: https://docs.vsuite.dev

# Repository
repo_name: vServerSuite/vDocumentation
repo_url: https://github.com/vServerSuite/vDocumentation

# Copyright
copyright: Copyright &copy; 2020 vSuite

theme:
  name: material
  language: en
  palette:
    primary: '#101d2d'
    accent: '#2174ea'
  font:
    text: Inter
    code: Fira Code

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vServerSuite

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
